export const catalogo = [ 
{ id: 1, titulo: "Rocket League", categoria: "Deportes/Acción", anio: 2015, destacado: false, imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Rocket_League_coverart.jpg/250px-Rocket_League_coverart.jpg"}, 
{ id: 2, titulo: "Warframe", categoria: "Shooter/RPG", anio: 2013, destacado: true, imagen:"https://imgs.search.brave.com/-9-kg-43fnD5JPChsZ1yG3a9eHD8arFWMMZshs_YHM4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1QllXTm1PR05p/T1RRdE5qRmxaUzAw/TmpZekxXSTVZekV0/TW1Nd01XVmlNVEF6/WldSalhrRXlYa0Zx/Y0djQC5qcGc"}, 
{ id: 3, titulo: "Jujutsu Kaisen", categoria: "Anime/Acción", anio: 2020, destacado: true, imagen:"https://imgs.search.brave.com/V0Oy1jx-JIWvIEjLweYFWSuGlNSr0jQypGLmFHpZSZ4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9qdWVn/b3NkaWdpdGFsZXNh/cmdlbnRpbmEuY29t/L2ZpbGVzL2ltYWdl/cy90aHVtYnMvcHJv/ZHVjdG9zXzMwMHg0/MDBfMTcwNjU0NjI0/OS1qdWp1dHN1LWth/aXNlbi1jdXJzZWQt/Y2xhc2gtcHM0LXBy/ZS1vcmRlbi0wLnBu/Zw" }, 
{ id: 4, titulo: "Hollow Knight", categoria: "Aventura/Indie", anio: 2017, destacado: false, imagen: "https://imgs.search.brave.com/tZJdTS7EDKf6XQZ-RyLYQ4QX4N1zGVXMRjmuMkxynxI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YXByb3h5LnR2dHJv/cGVzLm9yZy93aWR0/aC8xMjAwL2h0dHBz/Oi8vc3RhdGljLnR2/dHJvcGVzLm9yZy9w/bXdpa2kvcHViL2lt/YWdlcy9ob2xsb3df/a25pZ2h0X2FydF81/LmpwZw" }, 
{ id: 5, titulo: "Shingeki no Kyojin", categoria: "Anime/Drama", anio: 2013, destacado: true, imagen: "https://imgs.search.brave.com/NM3Rg78ggjWuE-iFNGU6CJ_NQ_5A7cqD2F76GFzqPxE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3c0/LmFuaW1lZmx2Lm5l/dC91cGxvYWRzL2Fu/aW1lcy9jb3ZlcnMv/Mzc2NC5qcGc" }, 
{ id: 6, titulo: "Minecraft", categoria: "Supervivencia", anio: 2011, destacado: false, imagen: "https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fminecrafts-cover-art-over-the-years-v0-iijtcp0anhje1.png%3Fwidth%3D1080%26crop%3Dsmart%26auto%3Dwebp%26s%3Dc04096656ad1f3b03838ad8a577c3aac8b464a96" }, 
{ id: 7, titulo: "Boku no Hero Academia", categoria: "Anime/Acción", anio: 2016, destacado: true, imagen: "https://imgs.search.brave.com/ZIaUwY4cnMG6X5vQ6KoNv3p2y9Q05pq8UIMEtWcjTX0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDE4OTM2/NjUuanBn" }, 
{ id: 8, titulo: "Elden Ring", categoria: "RPG/Acción", anio: 2022, destacado: true, imagen: "https://imgs.search.brave.com/irG-1aCgi236RoJsi-kH4u0TO_nXbIMkJmDnVxnwDDY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1QlpHUXhNall5/T1RVdE5qWXlNQzAw/TnpkbUxXSTRZbVl0/TURoaU9EVTNOamM1/WkRKa1hrRXlYa0Zx/Y0djQC5qcGc" }, 
{ id: 9, titulo: "Nanatsu no Taizai", categoria: "Anime/Aventura", anio: 2014, destacado: false, imagen: "" }, 
{ id: 10, titulo: "Stardew Valley", categoria: "Simulación/Indie", anio: 2016, destacado: true, imagen: "" }, 
{ id: 11, titulo: "Kimetsu no Yaiba", categoria: "Anime/Acción", anio: 2019, destacado: true, imagen: "" }, 
{ id: 12, titulo: "Cyberpunk 2077", categoria: "RPG/Mundo Abierto", anio: 2020, destacado: false, imagen: "" 
}, 
{ id: 13, titulo: "Death Note", categoria: "Anime/Misterio", anio: 2006, destacado: true, imagen:"" }, 
{ id: 14, titulo: "Red Dead Redemption 2", categoria: "Acción/Mundo Abierto", anio: 2018, 
destacado: true, imagen: "" }, 
{ id: 15, titulo: "One Piece", categoria: "Anime/Aventura", anio: 1999, destacado: false, imagen: "" }, 
{ id: 16, titulo: "Hades", categoria: "Roguelike/Indie", anio: 2020, destacado: true, imagen: "" }, 
{ id: 17, titulo: "Naruto Shippuden", categoria: "Anime/Acción", anio: 2007, destacado: false, imagen: "" }, 
{ id: 18, titulo: "The Legend of Zelda: Breath of the Wild", categoria: "Aventura", anio: 2017, 
destacado: true, imagen: "" }, 
{ id: 19, titulo: "Fullmetal Alchemist: Brotherhood", categoria: "Anime/Aventura", anio: 2009, 
destacado: true, imagen: "" }, 
{ id: 20, titulo: "God of War", categoria: "Acción/Aventura", anio: 2018, destacado: true, imagen: "" }, 
{ id: 21, titulo: "Persona 5 Royal", categoria: "JRPG", anio: 2019, destacado: false, imagen: "" }, 
{ id: 22, titulo: "Hunter x Hunter", categoria: "Anime/Aventura", anio: 2011, destacado: true, imagen: "" }, 
{ id: 23, titulo: "League of Legends", categoria: "MOBA", anio: 2009, destacado: false, imagen: "" }, 
{ id: 24, titulo: "Valorant", categoria: "Shooter Táctico", anio: 2020, destacado: false, imagen: "" }, 
{ id: 25, titulo: "Steins;Gate", categoria: "Anime/Ciencia Ficción", anio: 2011, destacado: true, imagen: "" },
{ id: 26, titulo: "The Witcher 3: Wild Hunt", categoria: "RPG/Aventura", anio: 2015, destacado: 
true, imagen: "" }, 
{ id: 27, titulo: "Dragon Ball Z", categoria: "Anime/Acción", anio: 1989, destacado: true, imagen:"" }, 
{ id: 28, titulo: "Celeste", categoria: "Plataformas/Indie", anio: 2018, destacado: false, imagen:"" }, 
{ id: 29, titulo: "Portal 2", categoria: "Puzzles", anio: 2011, destacado: true, imagen: "" }, 
{ id: 30, titulo: "Neon Genesis Evangelion", categoria: "Anime/Mecha", anio: 1995, destacado: 
true, imagen: "" }, 
{ id: 31, titulo: "Apex Legends", categoria: "Battle Royale", anio: 2019, destacado: false, imagen: "" }, 
{ id: 32, titulo: "Baldur's Gate 3", categoria: "RPG/Estrategia", anio: 2023, destacado: true, imagen: "" }, 
{ id: 33, titulo: "Bloodborne", categoria: "RPG/Acción", anio: 2015, destacado: false, imagen: "" }, 
{ id: 34, titulo: "Cowboy Bebop", categoria: "Anime/Ciencia Ficción", anio: 1998, destacado: true, imagen: ""               
}, 
{ id: 35, titulo: "Terraria", categoria: "Supervivencia/Indie", anio: 2011, destacado: false, imagen: "" } 
];