const imagenDefault = "https://via.placeholder.com/250x350?text=Sin+Imagen";
export const catalogo = [
{ id: 1, titulo: "Rocket League", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg"},
{ id: 2, titulo: "Warframe", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg"},
{ id: 3, titulo: "Jujutsu Kaisen", imagen: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg"},
{ id: 4, titulo: "Hollow Knight", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg"},
{ id: 5, titulo: "Shingeki no Kyojin", imagen: "https://cdn.myanimelist.net/images/anime/10/47347.jpg"},
{ id: 6, titulo: "Minecraft", imagen: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3a/Minecraft_cover.png"},
{ id: 7, titulo: "Boku no Hero Academia", imagen: "https://cdn.myanimelist.net/images/anime/10/78745.jpg"},
{ id: 8, titulo: "Elden Ring", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg"},
{ id: 9, titulo: "Nanatsu no Taizai", imagen: imagenDefault },
{ id: 10, titulo: "Stardew Valley", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg"},
{ id: 11, titulo: "Kimetsu no Yaiba", imagen: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg"},
{ id: 12, titulo: "Cyberpunk 2077", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg"},
{ id: 13, titulo: "Death Note", imagen: "https://cdn.myanimelist.net/images/anime/9/9453.jpg"},
{ id: 14, titulo: "Red Dead Redemption 2", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg"},
{ id: 15, titulo: "One Piece", imagen: "https://cdn.myanimelist.net/images/anime/6/73245.jpg"},
{ id: 16, titulo: "Hades", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg"},
{ id: 17, titulo: "Naruto Shippuden", imagen: "https://cdn.myanimelist.net/images/anime/5/17407.jpg"},
{ id: 18, titulo: "Zelda BOTW", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1458500/header.jpg"},
{ id: 19, titulo: "Fullmetal Alchemist", imagen: "https://cdn.myanimelist.net/images/anime/1223/96541.jpg"},
{ id: 20, titulo: "God of War", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg"},
{ id: 21, titulo: "Persona 5", imagen: imagenDefault },
{ id: 22, titulo: "Hunter x Hunter", imagen: "https://cdn.myanimelist.net/images/anime/1337/99013.jpg"},
{ id: 23, titulo: "League of Legends", imagen: imagenDefault },
{ id: 24, titulo: "Valorant", imagen: imagenDefault },
{ id: 25, titulo: "Steins;Gate", imagen: "https://cdn.myanimelist.net/images/anime/5/73199.jpg"},
{ id: 26, titulo: "The Witcher 3", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg"},
{ id: 27, titulo: "Dragon Ball Z", imagen: "https://cdn.myanimelist.net/images/anime/1607/117271.jpg"},
{ id: 28, titulo: "Celeste", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg"},
{ id: 29, titulo: "Portal 2", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg"},
{ id: 30, titulo: "Evangelion", imagen: "https://cdn.myanimelist.net/images/anime/1314/108941.jpg"},
{ id: 31, titulo: "Apex Legends", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg"},
{ id: 32, titulo: "Baldur's Gate 3", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg"},
{ id: 33, titulo: "Bloodborne", imagen: imagenDefault },
{ id: 34, titulo: "Cowboy Bebop", imagen: "https://cdn.myanimelist.net/images/anime/4/19644.jpg"},
{ id: 35, titulo: "Terraria", imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg"}
];